import {useState, useEffect} from 'react';
import { TextBox, ChatField } from '../components';

const Home = () => {
  const [messages, setMessages] = useState([]);
  useEffect(() => {
    setMessages(() => {
      return [
        {
          name: "Me",
          time: "11:30",
          message: "What is npm?"
        },
        {
          name: "Bot",
          time: "12:15",
          message: "Npm means node package manager that is used to develop node js applications. It is very good for development",
          extra: "Generated by, OpenAI"
        },
      ];
    })
  }, []);

  const generateAns = async (message) => {
    // * Do the API calling
  }

  return (
    <div className='flex flex-col-reverse justify-between'>
      <TextBox
        placeholder="Write down your query here"
        setValue={setMessages}
        messages={messages}
        generateAns={generateAns}
      />
      <ChatField messages={messages} />
    </div>
  )
}

export default Home;