const { OpenAI } = require("openai");
const TextPrompt = require("../models/text_prompt");
require("dotenv").config();
const config = {
  apiKey: process.env.OpenAI_API,
};

const openai = new OpenAI(config);

const savePrompt = async (name, message, extra, session) => {
  try {
    const date = new Date();
    const prompt = {
      name,
      time: `${date.getDate()}/${date.getMonth()}/${date.getFullYear()} ${
        date.getHours()
      }:${date.getMinutes()}`,
      message,
    };
    if (extra) {
      prompt.extra = "Generated by, OpenAI";
    }
    const textPromptCollection = await new TextPrompt(prompt);
    const textPrompt = await textPromptCollection.save({session});
    return textPrompt;
  } catch (err) {
    throw err;
  }
};

const getAllPrompt = async (session) => {
  try {
    const textPrompts = await TextPrompt.find().session(session).lean();
    if (textPrompts) {
      return textPrompts;
    } else {
      return [];
    }
  } catch (err) {
    throw err;
  }
};

const runPrompt = async (systemPrompt, mainPrompt, session) => {
  const messages = [
    { role: "system", content: `${systemPrompt}` },
    { role: "user", content: `${mainPrompt}` },
  ];
  try {
    const userPrompt = await savePrompt("Me", mainPrompt, false, session);
    const completion = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages,
      frequency_penalty: 0.7,
      max_tokens: 1000,
      temperature: 0.9,
    });
    console.log(completion);
    let sentence = "";
    for (const chunk of completion.choices) {
      console.log(chunk);
      sentence = sentence.concat(chunk.message.content);
    }
    if (sentence === "") {
      sentence = "Sorry, no info is found on this topic";
    }
    const botPrompt = await savePrompt("Bot", sentence, true, session);
    const messageList = await getAllPrompt(session);
    return messageList;
  } catch (err) {
    throw err;
  }
};

module.exports = {
  runPrompt,
  getAllPrompt,
};
